image: node:latest
test_server:
  before_script:
    - apt-get update
    - apt-get --yes --force-yes install rsync
  only:
    refs:
      - develop
  script:
      # Search for the ssh-agent  
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
      # Start the ssh-agent
    - eval $(ssh-agent -s)
      # Add the SSH Key stored in the SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
      # Create the .ssh folder hgfgyug yuiy
    - mkdir -p ~/.ssh
      # Prevent ssh public key confirmation 
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      # Install dependencies
    - npm install
    - npm run build
      # Copy (Synchronize) the files to the deployed server90834729472
    - rsync -avrc --delete --exclude=.env "$PWD/build" root@$SERVER_IP:/var/www/html/vendly/